#!/bin/sh

if [ "x$VERBOSE_LD" != "x" ]; then
CTT="$@"
case "$@" in
@/tmp/*)
C=$(echo "$@" | cut -c 2-)
CTT="$(cat "$C")"
;;
esac
echo "$CTT" >&2
fi

if [ "x$FORCE_GOLD" != "x" ]; then
exec $0.gold $@
fi

exec $0.bfd $@
